/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modulos;

import javax.swing.table.DefaultTableModel;


public class FacturaFinal extends javax.swing.JDialog {

    Factura factura;
    classes.Factura selected;
    DefaultTableModel modelo;
    
    public FacturaFinal(java.awt.Frame parent, boolean modal, Factura factura, classes.Factura selected) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.factura = factura;
        this.selected = selected;
        
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbNoFactura = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductosFacturaFinal = new rojerusan.RSTableMetro();
        jLabel10 = new javax.swing.JLabel();
        lbNombreVendedor = new javax.swing.JLabel();
        lbDui = new javax.swing.JLabel();
        lbTelefonoVendedor = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        subTotalFactura = new javax.swing.JLabel();
        descIVA = new javax.swing.JLabel();
        totalFactura = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(19, 22, 29));

        jLabel1.setBackground(new java.awt.Color(19, 22, 29));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("SISTEMA DE FACTURACIÓN");

        jLabel3.setBackground(new java.awt.Color(19, 22, 29));
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Colonia Valle de Jiboa #240, San Vicente, El Salvador");

        lbNoFactura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNoFactura.setForeground(new java.awt.Color(0, 0, 0));
        lbNoFactura.setText("FACTURA N° 0001");

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        jLabel4.setText("milogo.com");

        jLabel5.setBackground(new java.awt.Color(19, 22, 29));
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Email: system@system.com");

        jLabel6.setBackground(new java.awt.Color(0, 51, 102));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  FACTURAR A");
        jLabel6.setOpaque(true);

        lbNombre.setText("Nombre: Maria Magdalena Roque Bolaños");

        lbTelefono.setText("Telefono: 0000-0000");

        lbDireccion.setText("Dirección: Residencial los amates 5ta avenida Sur Casa #49");

        tablaProductosFacturaFinal.setBackground(new java.awt.Color(255, 255, 255));
        tablaProductosFacturaFinal.setForeground(new java.awt.Color(255, 255, 255));
        tablaProductosFacturaFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CANT", "DESCRIPCIÓN", "PRECIO UNIT", "PRECIO TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductosFacturaFinal.setAltoHead(20);
        tablaProductosFacturaFinal.setColorBackgoundHead(new java.awt.Color(0, 51, 102));
        tablaProductosFacturaFinal.setColorBordeFilas(new java.awt.Color(232, 232, 232));
        tablaProductosFacturaFinal.setColorBordeHead(new java.awt.Color(232, 232, 232));
        tablaProductosFacturaFinal.setColorFilasBackgound2(new java.awt.Color(232, 232, 232));
        tablaProductosFacturaFinal.setColorFilasForeground1(new java.awt.Color(0, 0, 51));
        tablaProductosFacturaFinal.setColorFilasForeground2(new java.awt.Color(0, 0, 51));
        tablaProductosFacturaFinal.setColorSelForeground(new java.awt.Color(51, 51, 51));
        tablaProductosFacturaFinal.setFocusable(false);
        tablaProductosFacturaFinal.setFuenteFilas(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tablaProductosFacturaFinal.setFuenteFilasSelect(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tablaProductosFacturaFinal.setFuenteHead(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tablaProductosFacturaFinal.setGridColor(new java.awt.Color(255, 255, 255));
        tablaProductosFacturaFinal.setGrosorBordeFilas(0);
        tablaProductosFacturaFinal.setGrosorBordeHead(0);
        tablaProductosFacturaFinal.setMultipleSeleccion(false);
        tablaProductosFacturaFinal.setRequestFocusEnabled(false);
        tablaProductosFacturaFinal.setRowSelectionAllowed(false);
        tablaProductosFacturaFinal.getTableHeader().setResizingAllowed(false);
        tablaProductosFacturaFinal.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaProductosFacturaFinal);
        if (tablaProductosFacturaFinal.getColumnModel().getColumnCount() > 0) {
            tablaProductosFacturaFinal.getColumnModel().getColumn(0).setResizable(false);
            tablaProductosFacturaFinal.getColumnModel().getColumn(0).setPreferredWidth(0);
            tablaProductosFacturaFinal.getColumnModel().getColumn(1).setResizable(false);
            tablaProductosFacturaFinal.getColumnModel().getColumn(1).setPreferredWidth(250);
            tablaProductosFacturaFinal.getColumnModel().getColumn(2).setResizable(false);
            tablaProductosFacturaFinal.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel10.setBackground(new java.awt.Color(0, 51, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("         VENDEDOR                                      DUI                     TELÉFONO                      FECHA        ");
        jLabel10.setOpaque(true);

        lbNombreVendedor.setText("Pedro Marquez Quintanilla Monteros");

        lbDui.setText("00000000-9");

        lbTelefonoVendedor.setText("0000-0000");

        lbFecha.setText("dd/MM/yyyy");

        subTotalFactura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subTotalFactura.setText("SUBTOTAL $");

        descIVA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descIVA.setText("IVA (13%) $");

        totalFactura.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        totalFactura.setText("TOTAL $");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subTotalFactura)
                    .addComponent(descIVA, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalFactura, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(192, 192, 192))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbNombreVendedor)
                        .addGap(46, 46, 46)
                        .addComponent(lbDui)
                        .addGap(75, 75, 75)
                        .addComponent(lbTelefonoVendedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbFecha)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTelefono)
                            .addComponent(lbNombre)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbDireccion)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(50, 50, 50)
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbNoFactura))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(202, 202, 202)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbNoFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTelefono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbDireccion)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNombreVendedor)
                            .addComponent(lbDui)
                            .addComponent(lbTelefonoVendedor)
                            .addComponent(lbFecha))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(subTotalFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(descIVA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalFactura)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FacturaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FacturaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FacturaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FacturaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FacturaFinal dialog = new FacturaFinal(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    
    public void mostrarDatos(){
        
        modelo = (DefaultTableModel)tablaProductosFacturaFinal.getModel();
        modelo.setRowCount(0); //Limpia la tabla
        
        lbNoFactura.setText("FACTURA N° 000" + selected.getNumero());
        lbNombre.setText("Nombre: " + selected.getCliente().getNombre());
        lbTelefono.setText("Teléfono" + selected.getCliente().getTelefono());
        lbDireccion.setText("Dirección: " + selected.getCliente().getDireccion());
        
        lbNombreVendedor.setText(selected.getVendedor().getNombre());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descIVA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbDui;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbNoFactura;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombreVendedor;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTelefonoVendedor;
    private javax.swing.JLabel subTotalFactura;
    private rojerusan.RSTableMetro tablaProductosFacturaFinal;
    private javax.swing.JLabel totalFactura;
    // End of variables declaration//GEN-END:variables
}
